project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Deskreview"
  favicon: images/favicon.svg
  site-url: https://www.deskreview.com
  twitter-card: true
  open-graph: true
  announcement:
    icon: info-circle
    dismissable: true
    content: "Website is under construction"
    type: warning
    position: below-navbar
    font-size: 1rem
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: images/nav-logo.webp
    logo-href: index.qmd
    title: false
    right:
      - text: Blog
        href: blog/index.qmd
      - text: About
        href: index.qmd
      
format:
  html:
    theme:
      light: scss/light.scss
    css: scss/styles.css
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable

editor: visual

